#!/bin/bash

export PLAYDATE_SDK_PATH="/Users/rzer/Developer/PlaydateSDK"
export GAME_NAME="HelloWorld"


cd "$(dirname "$0")"

export PLAYDATE_GAME_NAME="${GAME_NAME}"
rm -Rf build-arm
mkdir build-arm
cd build-arm
cmake -DCMAKE_TOOLCHAIN_FILE=$PLAYDATE_SDK_PATH/C_API/buildsupport/arm.cmake ..
make

